daos-stack/daos_scaled_testing

daos_server_psm2.yml, main.sh
Existing Stampede2 infrastructure cannot run with daos nopmix bootstrapping.
Changes are required in scripts and yaml file to select the correct server
access point in the sbatch job.
Update dmg tool and cmd.
Temporarily disabled DAOS_TEST, MDTEST and SELF_TEST.
=> DAOS-3891 Enable IOR to run with daos nopmix bootstrapping on Stampede2

main.sh, run_cart.sh
Changes in run_cart.sh and main.sh to use local hwloc and ompi build
This is to streamline the build process and have a better
build versioning control for validation
=> DAOS-4005 Streamline build and validation process

daos_server_verbs.yml, env_daos, main.sh
Correcting run_mdtest() to use total ranks as num procs * total clients.
Removing caching env from client and server env files as it was only.
needed due to a bug in cart but after it was updated this is not needed
anymore explicitly.
Removing singleton env variables from client env as it is deprecated.
Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>
=> Enabling mdtest in the main script with easy params

daos_server.yml
Set crt_timeout to 5min to have enough time to create bigger pool
Signed-off-by: Sylvia Oi Yee Chan <sylvia.oi.yee.chan@intel.com>
=> Update default value for crt_timeout in daos_server.yml

build_env.sh, get_ior_results.sh, run_build.sh, run_testlist.py, run_weekly.sh, source_me.sh, tests.sh
Automating 2 ior hard testcases:
- scaling server2client 1to4
- constant client count at 16, scaling server
Codebase enhancements
- Run python linter on run_testlist.py file
- Update get_ior_results.sh file to collec ior results
into a csv file
- Add a function to wait for all the DAOS servers to
be up or the function timeout
Signed-off-by: Martinez Montes, Jonathan <jonathan.martinez.montes@intel.com>
=> DAOS-5723 Automate IOR hard on Frontera for weekly run

get_ior_results.sh, get_mdtest_results.sh, print_node_local_time.sh, run_testlist.py, tests.sh
Automating 1 stabilization testcase
- Start DAOS with N servers
- Create a pool
- Randomly select and kill one server
- Wait until rebuild is completed
Add the teardown function. This function helps the slurm job
to finish early when the test fails and save compute time on the
cluster. Otherwise, the servers continue running until the slurm
job timeout.
=> DAOS-6024 Add stabilization test

cleanup.sh, copy_log_files.sh, daos_server.yml, env_daos, get_ior_results.sh, get_mdtest_results.sh, run_build.sh, run_testlist.py, tests.sh
* Add support to collect multiple data points from the
same build into the csv files.
* Save the repo information into a dedicated file.
* Refactor the run_testlist.py file.
* Kill all the child processes created by the testcase after
performing the teardown. This allow us to release the
slurm reservation as soon as the teardown function is
invocated, and the logs from all the nodes are saved.
* Add the ior easy-1to4 and easy-c16 testcases with
2-way and 3-way replication.
=> DAOS-4810: Add ior easy testcases with replication

run_testlist.py
Add mdtest easy testcases with with 2-way and 3-way replication.
=> DAOS-4812: Add mdtest easy with replication testcases

run_testlist.py
Add the ior hard with 2-way and 3-way replication.
=> DAOS-4811: Add ior hard testcases with replication

cleanup.sh, copy_log_files.sh, create_log_dir.sh, daos_server.yml, env_daos, mpich_gen_hostlist.sh, openmpi_gen_hostlist.sh, run_build.sh, run_sbatch.sh, run_testlist.py, tests.sh
* Use DAOS release build.
* Update the workaround to run DAOS on Frontera.
* Run DAOS on the target directory rather than running it on
a temporary directory and then moving/copy results.
* Add timeout option to run commands.
=> Minor fixes and enhancements

copy_log_files.sh, openmpi_gen_hostlist.sh, tests.sh
Re export new/missing env vars in the clush call to daos(8)
There was an incorrect path while creating the hostlist file
=> DAOS-6392: Fix container creation issue

daos_server.yml, env_daos, run_build.sh, run_sbatch.sh, run_testlist.py, tests.sh
* Enable FI_OFI_RXM_USE_SRX=1 in environment
* Increase ior-easy testvariants
* Build ior from upstream ior repo
* Store current TACC usage
* Run daos_agent only on client nodes
* Run dmg and daos tools from client nodes
* Remove dated --dfs.svcl flag
* Add --dfs.chunk_size flag
=> Miscellaneous fixes and enhancements

daos_server.yml, run_build.sh, run_build_on_compute_node.sh, run_build_sbatch.sh, tests.sh
* Propagate environment variables while running commands
with clush.
* Add script to build DAOS on a compute node.
Signed-off-by: Martinez Montes, Jonathan <jonathan.martinez.montes@intel.com>
=> DAOS-6908: Build DAOS on a compute node

copy_log_files.sh, create_log_dir.sh, daos_server.yml, run_testlist.py, tests.sh
Add a function to run daos_metrics on all the
server nodes to collect the telemetry data.
=> DAOS-6969: Add function to collect DAOS metrics

README.md, README.txt, build_and_install_tools.sh, get_ior_results.sh, get_mdtest_results.sh
- Added build_and_install_tools.sh
Builds and installs hwloc, openmpi, mpich.
- Some minor spelling errors and documentation updates
Co-authored-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>
=> add build_and_install_tools.sh

tests.sh
Manually create the container before calling mdtest.
This allows us to set container properties.
=> create cont before calling mdtest

tests.sh
Query the container and check daos status right after ior,
instead of going directly to teardown on failure. This lets us see
if a rank was evicted or pool ran out of space.
=> query cont right after ior

tests.sh
Add quotes around bash function arguments so they are interpreted
correctly.
For check_cmd_timeout, this does cause some of the STATUS messages to be
verbose, but for now at least TEARDOWN_ON_ERROR is passed correctly.
=> add quotes around bash function args

README.md, tests.sh
Use dmg pool create --properties instead of dmg pool set-prop.
Since this option was added in v1.3.103-tb, also remove
compatibility support for v1.3.102-tb.
Add a table of script/DAOS compatibilty to the README
=> use dmg pool create --properties

sbatch_me.txt
Exit with the rc from `tests.sh` instead of `rc=0` from the `tee` command
=> exit slurm job with correct rc

run_testlist.py, tests.sh
- run_testlist.py
- add MPI_TARGET to the env
- tests.sh
- use MPI_TARGET set in the env
- Set MPI_CMD in the beginning instead of each function
checking MPI_TARGET and deciding with prefix to use.
=> consolidate MPI_TARGET checks

frontera/run_testlist.py, frontera/tests.sh
- Support running ior write and read independently, but using the same
stonewall file.
- Also reduce the default setup_offset to 5, since it realistically only
takes up to 2-3 minutes even for 128 servers.
=> support ior write/read independent

frontera/build_and_install_tools.sh, frontera/get_results.py, frontera/run_build.sh, frontera/run_build_on_compute_node.sh, frontera/run_sbatch.sh, frontera/run_testlist.py, frontera/run_weekly.sh, frontera/tests.sh
- create container with label
- Create container with label
- Rename cont create and cont query
- Parameterize cont create and cont query
- print JOBNAME, EMAIL and remove some globals
- print JOBNAME and EMAIL
- remove some globally define vars
- address TODO items
- inflight doesn't need to be a variant at this time
- exit if RUN_DIR fails to be created, before scheduling the slurm job
- update and simplify path usage
- Install in $WORK by default, not $HOME or $SCRATCH
- Set default paths to actual paths
=> miscellaneous improvements

frontera/run_sbatch.sh, frontera/run_testlist.py, frontera/tests.sh, frontera/tests/README.md, frontera/tests/basic/ior_easy.py, frontera/tests/basic/ior_hard.py, frontera/tests/basic/mdtest_easy.py, frontera/tests/basic/mdtest_hard.py, frontera/tests/ec/ior_full_stripe.py, frontera/tests/ec/ior_partial_stripe.py, frontera/tests/ec_vs_rf0/ior_easy.py, frontera/tests/ec_vs_rf0/ior_hard.py, frontera/tests/ec_vs_rf0/mdtest_easy.py, frontera/tests/ec_vs_rf0/mdtest_hard.py, frontera/tests/rebuild/empty_ec.py, frontera/tests/rebuild/load_ec.py, frontera/tests/repl/ior_easy.py, frontera/tests/repl/ior_hard.py, frontera/tests/repl/mdtest_easy.py, frontera/tests/repl/mdtest_hard.py, frontera/tests/sanity/sanity.py, frontera/tests/self_test/self_test.py, frontera/tests/shard/shard.py
- Add `tests` directory with test configs
- Each config is a python file with a `tests` list defined
- `run_testlist.py`
- Add support for passing in the config paths
- Simplify core logic
=> support passing configs to run_testlist.py

frontera/README.md, frontera/tests.sh
- Update frontera/README.md
- tests.sh
- allow pool properties to be configured and nullable
- configurable IOR_ITER_DELAY (-d)
- rename IOR_WAIT_TIME to IOR_PHASE_DELAY
- when running both IOR write and read, don't use -W since read phase
will handle verfication
=> misc improvements

frontera/patches/ior_dedup_workaround.patch, frontera/run_build.sh
IOR patch to make all processes write the same data buffer.
This reduces per target space usage and allows runs with more client
processes.
=> ior dedup workaround patch

frontera/tests.sh, frontera/tests/basic/mdtest_easy.py, frontera/tests/basic/mdtest_hard.py, frontera/tests/ec_vs_rf0/mdtest_easy.py, frontera/tests/ec_vs_rf0/mdtest_hard.py, frontera/tests/ec_vs_rf0_simple/mdtest_easy.py, frontera/tests/ec_vs_rf0_simple/mdtest_hard.py, frontera/tests/repl/mdtest_easy.py, frontera/tests/repl/mdtest_hard.py, frontera/tests/sanity/mdtest.py
Read for mdtest easy is not useful.
Also rename extra_mdtest_params -> mdtest_flags.
=> remove read phase from mdtest easy

frontera/tests/ec_vs_rf0/ior_easy.py, frontera/tests/ec_vs_rf0/ior_hard.py, frontera/tests/ec_vs_rf0/mdtest_easy.py, frontera/tests/ec_vs_rf0/mdtest_hard.py, frontera/tests/ec_vs_rf0_simple/ior_easy.py, frontera/tests/ec_vs_rf0_simple/ior_hard.py, frontera/tests/ec_vs_rf0_simple/mdtest_easy.py, frontera/tests/ec_vs_rf0_simple/mdtest_hard.py
ec_cell_size is treated as a variant so it should be a test param, not
env var
=> fix ec_vs_rf ec_cell_size

frontera/tests.sh
=> pool create: use --size instead of --scm-size

frontera/run_testlist.py, frontera/tests.sh
- Don't print rf and ec cell size, since the command string contains it
- Don't explicitly set cont rf and ec cell size to the default
=> reduce output clutter

frontera/README.md, frontera/tests.sh, frontera/tests/sanity/rebuild.py
Stop referring to pool/cont uuids and instead always use labels.
Labels are more human-readable and eventually it will not be possible to
create a pool/cont with a user-generated uuid.
=> Stop using pool/cont uuids

frontera/daos_server.yml, frontera/env_daos, frontera/get_results.py
- parse provider in get_results.py
- add placeholder tcp and sockets env vars
=> frontera: config options for tcp and sockets

frontera/tests.sh
set at pool level instead of container to be backwards compatible
with UI change
=> frontera: set ec cell size on pool

edv/test_scripts/client/testlists/testlist_lammps.sh, edv/test_scripts/client/testlists/testlist_resnet.sh, edv/test_scripts/client/testlists/testlist_vpic.sh
Allow the user to specify the number of processes per node on the command-line for VPIC, LAMMPS and RENSET50 testlist scripts.
Also, replace user names with ${USER} to make the scripts easier to use for new users.
=> endeavour: set ppn on command-line

edv/test_scripts/client/scripts/collect_logs.sh, edv/test_scripts/client/scripts/run_client.sh, edv/test_scripts/client/scripts/run_client_resnet.sh
DAOS client and server logs are collected after an application completes. If that applciation hangs, is killed, or the script doesn't complete, logs are not collected. In these cases, we need a utility to collect logs.
Let's separate the functionality to collect all logs into a script and replace the code to collect logs in run_client.sh and run_client_resnet.sh with a call to this script.
=> endeavour: create collection of logs utility

edv/test_scripts/server/run_server.sh
In the server script run_server.sh, we call three other scripts to
clean up the servers, run the storage scan and start the servers.
We call clean_server.sh twice.  We should only call clean_server.sh
once.
=> endeavour: remove duplicate cleanup_server call

edv/test_scripts/client/scripts/run_client.sh, edv/test_scripts/client/testlists/testlist_lammps.sh, edv/test_scripts/client/testlists/testlist_resnet.sh, edv/test_scripts/client/testlists/testlist_vpic.sh
Darshan is an IO profiling tool. We’ve enabled Darshan for all applications run with the Endeavour test scripts using the “-d” flag on the testlist_* command line.
There are some limitations with this implementation:
- the Darshan library must be installed in ${CLIENT}./apps/${MPI}/darshan/lib/libdarshan.so
- the Darshan log will be created in the directory ${RESULTDIR}/darshanlog
=> endeavour: enable Darshan IO tracing

frontera/tests.sh
- Stop using --label with pool create
- Use remove compatibility check for --verbose with pool list
=> frontera: update pool commands

edv/test_scripts/client/scripts/run_client.sh
We have enabled running Darshan on Endeavour. We to fix the detection of when the LD_PRELOAD variable is set.
We also need to reduce the default amount of output written when the Interception Library is used.
=> endeavour: Modify Darshan Fix and IL Setting

edv/test_scripts/client/testlists/testlist_common.sh
We are missing a '&' in the last line of the testlist_common.sh script that checks the users command-line input. We use the double '&' to exit the script if a required variable is missing from the command-line.
=> endeavour: fix missing & in testlist_common.sh

frontera/tests.sh
There are places in tests.sh that we want to capture the return code of an mdtest or IOR command but record the return code of a different command.
=> frontera: collect correct return code

frontera/run_build.sh
The run_build script help lists "--timestamp" as a valid command-line option to set the time stamp for the build and dictate the path to install DAOS. We get an error if we try to use the --timestamp option.
=> frontera: parse timestamp command-line

edv/test_scripts/client/scripts/run_client.sh, edv/test_scripts/client/testlists/testlist_common.sh, edv/test_scripts/client/testlists/testlist_efispec.sh, edv/test_scripts/client/testlists/testlist_lammps.sh, edv/test_scripts/client/testlists/testlist_vpic.sh
The Endeavour scripts currently only use the ioil Interception Library. We need to allow for use of pil4dfs Interception Library.
The ‘-i’ command-line option will be redefined from the binary meaning of use the interception library (1) or don’t use the library (0) to specifying which interception library to use; ‘ioil’ or ‘pil4dfs’.
=> endeavour: allow use of pil4dfs IL

frontera/run_build.sh, frontera/utils/build_install_pciutils
A PR landed to the DAOS master (PR #14395) and DAOS release/2.6 (PR #14845) branches that requires the pciutils package.  Add detection and installation of pciutils to the frontera build process.
=> frontera: build pciutils

database/src/client/workbook.py
When it could be an exponent. For example
2e4 is interpreted as 2^4
=> workbook.py: fix float conversion
