gen_hostlist.sh, main.sh, run_cart.sh
Enable selftest to run with test_group
=> DAOS-3943 Enable selftest to run with test_group

daos_server_verbs.yml, env_daos, main.sh, run_cart.sh
Signed-off-by: Samirkumar Raval <samirrav@intel.com>
=> Code fix for IB (ofi+verbs).

daos_control.yml, env_daos, gen_hostlist.sh, main.sh
Launching daos_server and daos_agent with clush
Switching from orterun to mpich for launching client apps
Signed-off-by: Sylvia Chan <sylvia.oi.yee.chan@intel.com>
=> Enable ior and mdtest to run with daos master

env_daos
Update PATH and LD_LIBRARY_PATH to include prereq lib
=> Update env to include prerequisite libraries

run_build.sh, run_sbatch.sh, run_testlist.py, tests.sh
Automating 2 ior easy testcases:
- scaling server2client 1to4
- constant client count at 16, scaling server
Signed-off-by: Sylvia Chan <sylvia.oi.yee.chan@intel.com>
=> DAOS-5742 Automate IOR easy on Frontera for weekly run

run_testlist.py, tests.sh
* Split IOR read and write tests
* Add function to create and query multiple pools
* Add SWIM test with pool filled with IOR
* IOR stonewalling can be enabled/disabled from json
=> DAOS-3688: Improve SWIM tests

run_testlist.py
=> Update mdtest number of files

edv_scripts/icelake, edv_scripts/launch_daos_servers, edv_scripts/mount_dfuse.sh, edv_scripts/run_lammps_test.sh, edv_scripts/run_vpic_test.sh
Scripts for launching, mounting dfuse, running lammps, and run VPIC
test.
Also includes the hostfile for icelake nodes
Signed-off-by: Vishwanath Venkatesan <vishwanath.venkatesan@intel.com>
=> Endeavor scripts

get_results.py, tests.sh
- tests.sh
- Remove sleep after pool create
- get_results.py
- Remove old functions
- More error checking
- Improve rebuild parsing
=> Rebuild improvements

README_database.md, db.cnf, db.py, python3_requirements.txt, utils/db_call.py, utils/db_import.py, utils/db_report.py, utils/db_utils.py, utils/init_db.sql, utils/io_utils.py
Adds utilities for storing and retrieving test results in a SQL
database.
- New "utils" directory for common code
- init_db.sql
- sql tables, procedures, functions
- db.cnf
- sql config
- db.py
- wrapper for db utilities
- db_util.py
- utilities for interacting with mariadb
- db_import.py
- import csv into a table
- db_call.py
- call sql procedure
=> Store results in a SQL database

run_build.sh
Add the newest build patches to run_build.sh
=> Add build patches

tests.sh
=> fix bug with default CONT_PROP

run_build.sh
=> add pyelftools dependency

run_testlist.py
Signed-off-by: Samir Raval <samir.raval@intel.com>
=> Fix the EC unaligned stripe test name.

get_results.py
- get_results.py
- Get num_targets for ior and mdtest
=> get targets for ior and mdtest

tests.sh
Set some dmg compatibility options to work with older
and newer DAOS versions by checking the corresponding --help output.
- dmg pool list --verbose
- new option. Necessary to get full UUID
- dmg pool query --pool
- old option for compatibility
- dmg pool set-prop --pool
- old option for compatibility
=> handle dmg compatibility options

run_build.sh
Automatically merge the corresponding hack branch
depending on the git ancestry.
=> auto-merge hack branches

tests.sh
- Try to create pools with a label.
- Refactor dmg_pool_create
- Rename dmg_pool_create_multi
=> dmg pool create --label

run_build.sh
Silences a server error about nvme scan
=> new hack branch for building af19e7f

get_results.py, run_testlist.py
- Converted list of tests to dictionary of tests
- Made oclass a variant
- Consolidated ior and mdtest variants
- Added more ior and mdtest oclass variants
- Comment out ior and mdtest variants by defualt to avoid
accidentally running too many variants
- Basic environment compatibility checks
=> testlist improvements

get_results.py, poll_and_get_results.py, run_build.sh
Change daltonx to dalton per internal id change
=> change daltonx to dalton

frontera/convert_org.py, frontera/env_daos, frontera/get_results.py, frontera/run_sbatch.sh, frontera/sbatch_me.txt, frontera/tests.sh
- Copy daos configs to the slurm directory before the job starts
- Reorganize all job artifacts into the slurm directory
=> copy configs before job starts

frontera/get_results.py, frontera/tests.sh, frontera/tests/cart/cart.py
- new cart test skeleton
- get cart results in get_results.py
- can be enhanced in the future as needed
=> new cart test skeleton

frontera/run_build.sh
=> new hack branch based on 3e37280

frontera/get_results.py, frontera/tests.sh, frontera/tests/rebuild/load_ec.py
- Increased rebuild test scale
- add oclass to rebuild result csv
- more rebuild error checking
=> misc rebuild updates

frontera/run_build.sh
=> hack branch for daos release/2.0 commit b7a8e51

frontera/run_build.sh
=> hack branch based on f15d6c9

frontera/run_build.sh
- run_build.sh
- Allow passing parameters at the command line.
- Convert all core logic to functions
=> parameterize run_build.sh

frontera/run_build.sh
=> hack branch dbohning-io500-base-0fd0d78

frontera/run_build.sh
=> hack branch dbohning-io500-base-ec8f3d7

frontera/daos_server.yml
=> update server config to new format

frontera/tests/max/max.py
Maximum configuration with ior easy
=> Add tests/max/max.py

frontera/run_sbatch.sh, frontera/run_testlist.py
=> support some slurm deps

frontera/run_sbatch.sh, frontera/run_testlist.py
=> frontera: add option to run jobs serially

frontera/run_build.sh
=> frontera: new hack branches

frontera/tests.sh
=> frontera: daos_pool_query and misc cleanup

frontera/run_build.sh
=> frontera: new hack branch

frontera/run_build.sh
=> hack branch

frontera/run_build.sh, frontera/tests.sh
=> frontera: new hack branch and use ec_cell_sz

edv/test_scripts/client/testlists/testlist_lammps.sh, edv/test_scripts/client/testlists/testlist_resnet.sh, edv/test_scripts/client/testlists/testlist_vpic.sh
Add the ability to change script variable values with command-line
flags. The following testlist scripts were modified:
testlist_vpic.sh
testlist_lammps.sh
testlist_resnet.sh
The command-line flags are consistent across these testlist scripts.
These changes were provided by Ravindran Padmanabhan.
=> endeavour: add set script vars from command-line

frontera/patches/ior_dedup_workaround.patch, frontera/run_build.sh, frontera/tests.sh
=> frontera: lots more hacks

frontera/daos_server.yml, frontera/run_build.sh
=> frontera: config and build  updates

frontera/build_env.sh, frontera/daos_server.yml, frontera/patches/daos_scons_env_option.patch, frontera/patches/daos_scons_linkage.patch, frontera/run_build.sh, frontera/run_testlist.py, frontera/tests.sh
=> frontera: support build with current env

frontera/run_testlist.py
=> frontera: fix accidental change

frontera/patches/amd_scons_env.patch.df1f8034e516b5887a37ae4733d39cbd669612ea, frontera/patches/daos_scons_env_option.patch.6a3c9910ea2a7b647f818bed9754bb3363b78770, frontera/patches/daos_scons_linkage.patch.6a3c9910ea2a7b647f818bed9754bb3363b78770, frontera/run_build.sh
=> build updates for v2.3.103-tb

frontera/run_build.sh, frontera/utils/build_install_lmdb, frontera/utils/check_for_lib, frontera/utils/empty_main.c
- build lmdb from source
- new hack branch
- misch build improvments
=> frontera: build updates

edv/test_scripts/client/testlists/testlist_common.sh, edv/test_scripts/client/testlists/testlist_efispec.sh, edv/test_scripts/client/testlists/testlist_lammps.sh
The testlist/testlist_<app_name>.sh scripts start and run application app_name.  Each of these scripts have common code to parse and check the command line parameters. Collect these common functions into a new script that can be sourced by all testlist application scripts.
=> endeavour: collect common testlist functions

frontera/patches/daos_scons_linkage.patch.db6ac13c819d8053e5a94541be2d6df0fcd11a2b, frontera/run_build.sh
patches/daos_scons_linkage.patch.db6ac13c819d8053e5a94541be2d6df0fcd11a2b
=> frontera: new patch for scons

frontera/patches/daos_scons_linkage.patch.db6ac13c819d8053e5a94541be2d6df0fcd11a2b
adjust daos_scons_linkage.patch.db6ac13c819d8053e5a94541be2d6df0fcd11a2b
=> frontera: adjust scons patch

edv/test_scripts/client/testlists/testlist_vpic.sh
Convert the VPIC testlist file, testlist/testlist_vpic.sh, to use the common commnd-line parsing functions found in
testlist/testlist_common.sh
=> endeavour: VPIC testlist to use common functions

LICENSE
=> SRE-2521: New LICENSE file as expected by OpenSSF Scorecard
